##########################
#### USER
##########################
### Register
POST http://localhost:8001/api/register HTTP/1.1
Content-Type: application/json

{
    "name":"test",
    "email":"test@email.come",
    "password":"test"
}

### Login
POST http://localhost:8001/api/login HTTP/1.1
Content-Type: application/json

{
    "email":"test@email.come",
    "password":"test"
}

##########################
#### SURVEY
##########################

### Get all surveys
GET http://localhost:8001/api/surveys

### Get all survey for user
GET http://localhost:8001/api/survey

### Get single survey
GET http://localhost:8001/api/survey/60bc5a41ac01bfa3c2375f78 HTTP/1.1

### Create survey
POST http://localhost:8001/api/survey HTTP/1.1
Content-Type: application/json

{
    "name":"Survey 1",
    "description":"survey 1khdsifk"
}

### Update survey
PUT http://localhost:8001/api/survey/60bc5a41ac01bfa3c2375f78 HTTP/1.1
Content-Type: application/json

{
    "name":"Survey 2",
    "description":"Survey 2 update"
}

### Delete Survey

DELETE http://localhost:8001/api/survey/60bc5a41ac01bfa3c2375f78 HTTP/1.1